# 9. Interpretación de Resultados

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
filename = '../Data/selected_model.sav'

loaded_model = pickle.load(open(filename, 'rb'))

In [8]:
filename = '../Data/scaler.sav'
scaler = pickle.load(open(filename, 'rb'))

In [5]:
loaded_model.coef_[0]

array([ 0.        ,  0.10963108,  0.1038697 ,  0.04616007,  0.06948329,
        0.05769939,  0.0471353 , -0.01644888, -0.01724367, -0.0187684 ,
       -0.03648172])

In [6]:
with open("../Data/regressor_columns_def2.pickle", "rb") as fp:   #Pickling
...   regressor_columns_def = pickle.load(fp)

In [21]:
df = pd.read_csv('../Data/Ames-Housing-regressor-columns.csv', delimiter=',')

In [7]:
regressor_columns_def

['Overall Qual',
 'Gr Liv Area',
 'Garage Area',
 'Year Built',
 '1st Flr SF',
 'Year Remod/Add',
 'Full Bath',
 'Garage Yr Blt',
 'Kitchen Qual_TA',
 'Fireplace Qu_Sin categoria']

En base al modelo seleccionado, podemos hacer las siguientes conclusiones:

- El intercepto es 0. Tiene sentido que casa sin area o garajes no tenga valor, en vez de un valor negativo o positivo.
- Las variables de mayor peso son 'Overall Qual' y 'Gr Liv Area'. Tiene sentido que a mayor area vivible la casa cueste más, y a mayor calidad también se presente un incremento en el precio.
- Se tienen las siguiente variables con influencia negativa:
  1. 'Full Bath': Es contraintuivo que esta variable presente influencia negativa. A primera instancia, uno podría considerar que más baños completos deberían incrementar el precio.
  2. 'Garage Yr Blt': Puede indicar que casas más antiguas son consideradas más valiosas.
  3. 'Kitchen Qual_TA': La presencia de una cocina de calidad medio puede afectar el precio en relación con cocinas más caras y lujosas.
  4. 'Fireplace Qu_Sin categoria': Esto indica que una casa no tiene chimenea, lo cual afectar negativamente su precio
- Podrían analizarse la posibilidad de incluir más variables como estrato, número de baños, area de piscina, etc. que podría también afectar el precio.
- El uso de estandarización complica el analisis en términos prácticos de los coeficientes. Pero usando la información entregada por el scaler y recordando el hecho que algunas variables fueron transformadas con logaritmos, podemos hacer algunas conclusiones: 

Variables transformadas:

['Misc Val', 'Pool Area', 'Lot Area', 'Low Qual Fin SF', '3Ssn Porch', 'Kitchen AbvGr', 'BsmtFin SF 2', 'Enclosed Porch', 'Screen Porch', 'Bsmt Half Bath', 'Mas Vnr Area', 'Open Porch SF', 'Wood Deck SF', **'SalePrice'**, 'Lot Frontage', '1st Flr SF', 'BsmtFin SF 1', 'MS SubClass', **'Gr Liv Area'**, 'Total Bsmt SF']

In [40]:
df[regressor_columns_def].mean()

Overall Qual                     6.079041
Gr Liv Area                      7.252095
Garage Area                    462.899499
Year Built                    1971.761445
1st Flr SF                       6.996249
Year Remod/Add                1984.273605
Full Bath                        1.555794
Garage Yr Blt                 1978.094421
Kitchen Qual_TA                  0.516810
Fireplace Qu_Sin categoria       0.489270
dtype: float64

In [36]:
scaler.mean_

array([   6.05500894,    7.2515605 ,  459.64177102, 1970.99150268,
          6.99286316, 1983.99910555,    1.55679785, 1977.53577818,
          0.51744186,    0.50044723])

In [47]:
scaler.var_**0.5

array([  1.29817436,   0.29763639, 196.10613075,  29.5650252 ,
         0.30611567,  20.82104943,   0.53239706,  24.23199715,
         0.49969569,   0.4999998 ])

## Ground Living area

Ground living area fue transformada logaritmicamente, por lo que cualquier cambio debe ser aplicada la misma transformación. Por ejemplo entonces, si quisieramos ver cuanto afecta un cambio en 100 ft2 en el area habitable al precio, nos daría un incremento en el valor aproximado de 4 USD.

In [65]:
np.expm1((np.log1p(100)/(scaler.var_[1]**0.5))*loaded_model.coef_[0][2])

np.float64(4.005780772252273)